# src/OC/PlatformBundle/Ressources/config/routing.yml

##ATTENTION, PENSER AU PREFIX /PLATFORM CONFIGURE DANS APP/CONFIG/ROUTING.XML

#test
hello_the_world:
    path: /hello-world
    defaults: {_controller: OCPlatformBundle:Advert:indexTest}
    
#test
byebye_the_world:
    path: /byebye-world
    defaults: {_controller: OCPlatformBundle:Advert:bye}
    
#test
oc_platform_view_slug:
    path:    /{year}/{slug}.{_format}
    defaults:
        _controller: OCPlatformBundle:Advert:viewSlug
        _format: html
    requirements:
        year: \d{4}
        _format: html|xml

        
        
##
#véritable plateforme
##

oc_platform_home:
    path:    /{page}
    defaults:
        _controller: OCPlatformBundle:Advert:index
        page: 1
    requirements:
        page: \d*
        
oc_platform_view:
    path:    /advert/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:view
    requirements:
        id: \d+
        

oc_platform_add:
    path:    /add
    defaults:
        _controller: OCPlatformBundle:Advert:add

oc_platform_edit:
    path:    /edit/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:edit
    requirements:
        id: \d+    

oc_platform_delete:
    path:    /delete/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:delete
    requirements:
        id: \d+