# src/OC/PlatformBundle/Ressources/config/routing.yml

oc_core_homepage:
    path:     /
    defaults: { _controller: OCCoreBundle:Home:index }
    
oc_core_contact:
    path:     /contact
    defaults: { _controller: OCCoreBundle:Home:contact }
